version: '3'
services:
  website:
    image: shiningrush/website:latest
    ports:
      - "80:80"
  blog:
    image: shiningrush/blog:latest
  resume:
    image: shiningrush/resume:latest
  ss:
    image: shadowsocks/shadowsocks-libev:latest
    environment:
    - "PASSWORD=simplepassword"
    ports:
    - "8388:8388"
    - "8388:8388/udp"