version: '3'
services:
  website:
    image: shiningrush/website:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  blog:
    image: shiningrush/blog:latest
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
  resume:
    image: shiningrush/resume:latest
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
  trojan-go:
    image: p4gefau1t/trojan-go:latest
    depends_on:
      - "website"
    volumes:
      - ./certbot/conf/:/etc/nginx/ssl/:rw
      - ./conf/server.json:/etc/trojan-go/config.json
    ports:
      - "4430:4430"
