version: '3'
services:
  website:
    image: shiningrush/website:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  blog:
    image: shiningrush/blog:latest
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
  resume:
    image: shiningrush/resume:latest
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
  ss:
    image: shadowsocks/shadowsocks-libev:latest
    environment:
      - PASSWORD=simplepassword
    ports:
      - "8388:8388"
      - "8388:8388/udp"